import type { ConfigFieldMeta, ConfigKey } from "./types.js";

/** Syncplay-compatible INI sections (see ConfigurationGetter._iniStructure). */
export const INI_STRUCTURE: Record<string, ConfigKey[]> = {
  server_data: ["host", "port", "password"],
  client_settings: [
    "name",
    "room",
    "roomList",
    "playerPath",
    "perPlayerArguments",
    "slowdownThreshold",
    "rewindThreshold",
    "fastforwardThreshold",
    "folderSearchFirstFileTimeout",
    "folderSearchTimeout",
    "folderSearchDoubleCheckInterval",
    "folderSearchWarningThreshold",
    "slowOnDesync",
    "rewindOnDesync",
    "fastforwardOnDesync",
    "dontSlowDownWithMe",
    "forceGuiPrompt",
    "filenamePrivacyMode",
    "filesizePrivacyMode",
    "unpauseAction",
    "pauseOnLeave",
    "readyAtStart",
    "autoplayMinUsers",
    "autoplayInitialState",
    "mediaSearchDirectories",
    "sharedPlaylistEnabled",
    "loopAtEndOfPlaylist",
    "loopSingleFiles",
    "autoplayRequireSameFilenames",
    "onlySwitchToTrustedDomains",
    "trustedDomains",
    "publicServers",
  ],
  gui: [
    "autosaveJoinsToList",
    "showOSD",
    "showOSDWarnings",
    "showSlowdownOSD",
    "showDifferentRoomOSD",
    "showSameRoomOSD",
    "showNonControllerOSD",
    "showDurationNotification",
    "chatInputEnabled",
    "chatInputFontUnderline",
    "chatInputFontFamily",
    "chatInputRelativeFontSize",
    "chatInputFontWeight",
    "chatInputFontColor",
    "chatInputPosition",
    "chatDirectInput",
    "chatOutputFontFamily",
    "chatOutputRelativeFontSize",
    "chatOutputFontWeight",
    "chatOutputFontUnderline",
    "chatOutputMode",
    "chatMaxLines",
    "chatTopMargin",
    "chatLeftMargin",
    "chatBottomMargin",
    "chatMoveOSD",
    "chatOSDMargin",
    "notificationTimeout",
    "alertTimeout",
    "chatTimeout",
    "chatOutputEnabled",
    "showContactInfo",
  ],
  general: ["language", "checkForUpdatesAutomatically", "lastCheckedForUpdates"],
  splatty: ["playerKind", "setupComplete"],
};

export const CONFIG_FIELDS: ConfigFieldMeta[] = [
  { key: "name", section: "Connection", label: "Username", type: "string" },
  { key: "host", section: "Connection", label: "Server", type: "string" },
  { key: "port", section: "Connection", label: "Port", type: "number" },
  { key: "room", section: "Connection", label: "Room", type: "string" },
  { key: "password", section: "Connection", label: "Password", type: "string" },
  { key: "playerPath", section: "Connection", label: "Player path", type: "string" },
  { key: "playerKind", section: "Connection", label: "Player kind", type: "playerKind" },
  { key: "mediaSearchDirectories", section: "Connection", label: "Media directories", type: "string[]" },
  { key: "perPlayerArguments", section: "Connection", label: "Per-player arguments", type: "record" },
  { key: "roomList", section: "Connection", label: "Room list", type: "string[]" },

  { key: "readyAtStart", section: "Readiness", label: "Ready at start", type: "boolean" },
  { key: "pauseOnLeave", section: "Readiness", label: "Pause on leave", type: "boolean" },
  { key: "unpauseAction", section: "Readiness", label: "Unpause action", type: "unpause" },
  { key: "autoplayInitialState", section: "Readiness", label: "Autoplay initial state", type: "boolean" },
  { key: "autoplayMinUsers", section: "Readiness", label: "Autoplay min users", type: "number" },
  { key: "autoplayRequireSameFilenames", section: "Readiness", label: "Autoplay require same filenames", type: "boolean" },

  { key: "slowdownThreshold", section: "Sync", label: "Slowdown threshold (s)", type: "number" },
  { key: "rewindThreshold", section: "Sync", label: "Rewind threshold (s)", type: "number" },
  { key: "fastforwardThreshold", section: "Sync", label: "Fast-forward threshold (s)", type: "number" },
  { key: "rewindOnDesync", section: "Sync", label: "Rewind on desync", type: "boolean" },
  { key: "slowOnDesync", section: "Sync", label: "Slow on desync", type: "boolean" },
  { key: "fastforwardOnDesync", section: "Sync", label: "Fast-forward on desync", type: "boolean" },
  { key: "dontSlowDownWithMe", section: "Sync", label: "Never slow down others", type: "boolean" },
  { key: "trustedDomains", section: "Sync", label: "Trusted domains", type: "string[]" },
  { key: "onlySwitchToTrustedDomains", section: "Sync", label: "Only switch to trusted domains", type: "boolean" },
  { key: "publicServers", section: "Sync", label: "Public servers", type: "string[]" },

  { key: "filenamePrivacyMode", section: "Privacy", label: "Filename privacy", type: "privacy" },
  { key: "filesizePrivacyMode", section: "Privacy", label: "Filesize privacy", type: "privacy" },

  { key: "sharedPlaylistEnabled", section: "Playlist", label: "Shared playlist", type: "boolean" },
  { key: "loopAtEndOfPlaylist", section: "Playlist", label: "Loop at end of playlist", type: "boolean" },
  { key: "loopSingleFiles", section: "Playlist", label: "Loop single files", type: "boolean" },

  { key: "folderSearchFirstFileTimeout", section: "Folder search", label: "First file timeout (s)", type: "number" },
  { key: "folderSearchTimeout", section: "Folder search", label: "Search timeout (s)", type: "number" },
  { key: "folderSearchDoubleCheckInterval", section: "Folder search", label: "Double-check interval (s)", type: "number" },
  { key: "folderSearchWarningThreshold", section: "Folder search", label: "Warning threshold (s)", type: "number" },

  { key: "language", section: "General", label: "Language", type: "string" },
  { key: "checkForUpdatesAutomatically", section: "General", label: "Check for updates", type: "boolean" },
  { key: "forceGuiPrompt", section: "General", label: "Show setup on start", type: "boolean" },

  { key: "showOSD", section: "GUI (Syncplay)", label: "Show OSD", type: "boolean" },
  { key: "showOSDWarnings", section: "GUI (Syncplay)", label: "Show OSD warnings", type: "boolean" },
  { key: "showSlowdownOSD", section: "GUI (Syncplay)", label: "Show slowdown OSD", type: "boolean" },
  { key: "showSameRoomOSD", section: "GUI (Syncplay)", label: "Show same-room OSD", type: "boolean" },
  { key: "showDifferentRoomOSD", section: "GUI (Syncplay)", label: "Show different-room OSD", type: "boolean" },
  { key: "showNonControllerOSD", section: "GUI (Syncplay)", label: "Show non-controller OSD", type: "boolean" },
  { key: "showDurationNotification", section: "GUI (Syncplay)", label: "Show duration notification", type: "boolean" },
  { key: "showContactInfo", section: "GUI (Syncplay)", label: "Show contact info", type: "boolean" },
  { key: "chatInputEnabled", section: "GUI (Syncplay)", label: "Chat input enabled", type: "boolean" },
  { key: "chatOutputEnabled", section: "GUI (Syncplay)", label: "Chat output enabled", type: "boolean" },
  { key: "chatDirectInput", section: "GUI (Syncplay)", label: "Chat direct input", type: "boolean" },
  { key: "chatOutputMode", section: "GUI (Syncplay)", label: "Chat output mode", type: "string" },
  { key: "chatMaxLines", section: "GUI (Syncplay)", label: "Chat max lines", type: "number" },
  { key: "notificationTimeout", section: "GUI (Syncplay)", label: "Notification timeout (s)", type: "number" },
  { key: "alertTimeout", section: "GUI (Syncplay)", label: "Alert timeout (s)", type: "number" },
  { key: "chatTimeout", section: "GUI (Syncplay)", label: "Chat timeout (s)", type: "number" },
];

/** Aliases for /set and CLI — maps user-facing names to config keys. */
export const CONFIG_ALIASES: Record<string, ConfigKey> = {
  name: "name",
  username: "name",
  user: "name",
  host: "host",
  server: "host",
  port: "port",
  room: "room",
  password: "password",
  pass: "password",
  player: "playerKind",
  playerkind: "playerKind",
  "player-path": "playerPath",
  playerpath: "playerPath",
  media: "mediaSearchDirectories",
  "media-dirs": "mediaSearchDirectories",
  mediadirs: "mediaSearchDirectories",
  "media-directories": "mediaSearchDirectories",
  mediasearchdirectories: "mediaSearchDirectories",
  ready: "readyAtStart",
  readyatstart: "readyAtStart",
  language: "language",
  lang: "language",
  rooms: "roomList",
  "room-list": "roomList",
  servers: "publicServers",
  "public-servers": "publicServers",
  "player-args": "perPlayerArguments",
  playerargs: "perPlayerArguments",
};

for (const field of CONFIG_FIELDS) {
  CONFIG_ALIASES[field.key.toLowerCase()] = field.key;
}
